'''
In this project there will be a secret number generated by the computer we have to guess it!
'''
import random

def guess(x):
    random_number = random.randint(1,x)
    guess = 0
    while guess != random_number:
        guess = int(input(f"Guess a number between 1 and {x}: "))
        
        if guess < random_number:
            print("Sorry, guess again. too low")
        elif guess > random_number:
            print("Sorry, guess again. too high")
    
    print(f"Yay, you've guessed the number {random_number}")
    
guess(100)    
